---
title: "effect"
author: "zhu"
date: "26/12/2018"
output: pdf_document
---

```{r setup}
knitr::opts_chunk$set(echo = F,message = F,warning = F)
```
```{r source}
source(file = 'utils.R')
```
```{r data}
set.seed(999)
####pipeline#####
i=2#treatment
j=6#time
r=4#replicate
time=c(0,1,2,3,4,5)#time points
#y1 <- 0.01*time+0.01*time^2+0.01*time^3+0.01*time^4
ctrl <- 0.4*time
tre1 <- -0.4*time
tre2 <- -0.2*((time-2.5)^2)+0.5
tre3 <- c(0,0.3,1,0.4,0.6,2)
notrend <- rep(0,6)
y1 <- c(notrend)
y12 <- c(tre1)

y2 <- c(notrend)
y22 <- c(tre1)

y3 <- c(notrend)
y32 <- c(tre1)
#y12 <- 0.01*time^2

#y2 <- -time

#y3 <- c(-2,-1,0,0,1,2)
# y1 <- c(0,1,2,3,4,5)
#y32 <- 0.01*time^2
#y3 <- -0.01*time^3

#total of 100 metabolites(columns)
#total of 2*5*4=40 rows
```

```{r plot raw data metabolite one}
trend.toplot <- data.frame(replicate=rep(1:(i*j),each=r),time=rep(time,each=r),treatment=factor(rep(1:i,each=j*r)),metabolite=generate_data.same_var(p1 = 15,p2 = 15,p3 = 1,neg = 100,var = 0.2)$df[1,])
ggplot(trend.toplot,aes(x=time,y=metabolite,color=treatment))+
  geom_point()+
  stat_summary(fun.y = mean,geom = 'line')+
  labs(title = 'differentially expressed variable')
```

```{r}
effect <- function(which_leverage,
                   plot=FALSE,
                   pat_names.list=pat_names,
                   ftrs_in_pat.list=ftrs_in_pat,
                   replicates=r,
                   sd = sd,
                   method='to_fill_in',
                   effect,
                   R=5,
                   N=NULL,...){
  
  FPs <- vector()
  FNs <- vector()
  TPs <- vector()
  TNs <- vector()
  confusion_matrix <- vector()
  plots <- list()
  if (effect=='variables'){
    for (each in seq(N)){
      ftrs_in_pat.list[[length(ftrs_in_pat.list)]] <- N[each]
      #simulation <- generate_data.same_var(p1 = p1,p2 = p2,p3 = p3,neg = N[each],var=sd)
      simulation <- create.simulation(pat_names.list = pat_names.list,ftrs_in_pat.list = ftrs_in_pat.list,replicates = replicates,sd = sd,...)
      df.final <- simulation$df
      groups <- simulation$groups
      #design matrix
      asca.fit <- which_leverage(X = t(df.final),Designa = mx$j, Designb = mx$i,type = type, Fac = Fac,showvar = F,showscree = F)
      asca.fitted.original <- fitted(df.final,asca.fit,groups,R = R,which_leverage)
      plots[[each]] <- plot.leverage_spe(asca.fitted.original,sd=sd,title=paste('number of variables:',N[each],method))
      if (plot == TRUE){
        plot(plots)
      }
      confusion_matrix <- stats(asca.fitted.original$stats_for_plot)
      FPs[each] <- confusion_matrix$FP
      FNs[each] <- confusion_matrix$FN
      TPs[each] <- confusion_matrix$TP
      TNs[each] <- confusion_matrix$TN
    }
  }
  if (effect=='variances'){
    for (each in seq(N)){
      #simulation <- generate_data.same_var(p1 = p1,p2 = p2,p3 = p3,neg = neg,var=N[each])
      simulation <- create.simulation(pat_names.list = pat_names.list,ftrs_in_pat.list = ftrs_in_pat.list,replicates = r,sd = N[each],...)
      #simulation <- generate_data.nocorrelation(15,15,1,each)
      df.final <- simulation$df
      groups <- simulation$groups
      #design matrix
      asca.fit <- which_leverage(X = t(df.final),Designa = mx$j, Designb = mx$i,type = type, Fac = Fac,showvar = F,showscree = F)
      asca.fitted.original <- fitted(df.final,asca.fit,groups,5,which_leverage)
      plots[[each]] <- plot.leverage_spe(asca.fitted.original,sd=N[each],title=paste('variance:',N[each],method))
      if (plot == TRUE){
        plot(plots)
      }
      confusion_matrix <- stats(asca.fitted.original$stats_for_plot)
      FPs[each] <- confusion_matrix$FP
      FNs[each] <- confusion_matrix$FN
      TPs[each] <- confusion_matrix$TP
      TNs[each] <- confusion_matrix$TN
    }
  }
  effect_df <- list(method=rep(method,each=length(N)),effects=N,
  FP = FPs,
  FN = FNs,
  TP = TPs,
  TN = TNs,
  plots = plots %>% 
    set_names(N))
  effect_df
}
```
```{r  effect of number of variables}
i <- 2#treatment
j <- 6#time
r <- 4#replicate
time <- c(0,1,2,3,4,5)#time points
sd <- 0.2
fluctuate <- list(2,-2,2,-2,2,-2)
notrend <- rep(list(0),6)
ctrl <- notrend
tre1 <- fluctuate
tre2 <- fluctuate

trend1 <- append(ctrl,tre1)
trend2 <- append(ctrl,tre2)
trend3 <- append(ctrl,tre2)
trend4 <- append(ctrl,ctrl)
ftrs_in_pat <- list(30,30,1,100)
pat_names <- list('one','two','three','flat')
N1 <- c(150,170,190,200,300,400,500,700,900,1000,2000,3000,3500,4000,4500,5000)
N <- c(0.2,0.3)
#fit model
type=1
Fac=c(1,1,1,1)
mx <- asca.design.matrix(i,j,r,time)
#effect_df.original <- effect(ASCA.2f,plot = F,sd=0.2,N=N,method = 'asca_original',effect = 'variables')
effect_df.improved <- effect(which_leverage = ASCA.2f_leverage,
                             plot = F,
                             sd=0.2,
                             method = 'asca_improved',
                             effect = 'variables',
                             R=1,
                             pat_names.list = pat_names,
                             ftrs_in_pat.list = ftrs_in_pat,
                             replicates = r,
                             N=N1,
                             trend1,trend2,trend3,trend4)
variance_effect <- effect(which_leverage = ASCA.2f_leverage,
                          plot = F,
                          sd=N,
                          method = 'asca_improved',
                          effect = 'variances',
                          R=1,
                          pat_names.list = pat_names,
                          ftrs_in_pat.list = ftrs_in_pat,
                          replicates = r,
                          N=NULL,
                          trend1,trend2,trend3,trend4)
```
```{r}
ggplot(effect_df.original,aes(x=effects,y=FN,colour=method))+
  geom_line()+
  geom_line(data = effect_df.improved,aes(x=effects,y=FN))
ggplot(effect_df.original,aes(x=effects,y=FP,colour=method))+
  geom_line()+
  geom_line(data = effect_df.improved,aes(x=effects,y=FP))
```




