setwd(dir = "~/Desktop/Internship1/ASCA-genes.1.2.1/")
source("ASCA2f.R")
source("ASCA3f.R")
source("ASCAfun1.R")
source("ASCAfun2.R")
source("ASCAfunres.R")
source("ASCAfun12.R")
source("ASCAfun-triple.R")
source("PCA-GENES.R")
source("sceeplot.R")
source("show.var.R")
source("leverage.lims.R")
source("SPE.lims.R")
setwd('../')
